/**
 * Countries, for the one on a profile.
 *
 * Stored as an **ISO 3166-1 alpha-2 code** — `US`, not "United States" and not
 * "usa". The field was free text, which is fine until you want to draw a flag
 * next to it or count how many players are from one place: "UK", "U.K.",
 * "United Kingdom" and "england" are four countries to a database and one to a
 * reader.
 *
 * Only the codes are listed. Names come from `Intl.DisplayNames`, which every
 * runtime this site targets ships with its own ICU copy of — writing 250 names
 * out by hand would be 250 chances to misspell one, and they would be in
 * English forever. The list itself was generated by asking ICU which two-letter
 * codes it resolves, minus the deprecated and reserved ones it still answers
 * for (`SU` for the Soviet Union, `UK` which has never been the code for the
 * United Kingdom, the `XA`/`XB` testing codes).
 *
 * `XK` is kept although it is user-assigned rather than official: Kosovo is
 * where some players are from, and every flag source draws it.
 */
export const COUNTRY_CODES: readonly string[] = [
  'AD', 'AE', 'AF', 'AG', 'AI', 'AL', 'AM', 'AO', 'AQ', 'AR', 'AS', 'AT', 'AU', 'AW', 'AX', 'AZ',
  'BA', 'BB', 'BD', 'BE', 'BF', 'BG', 'BH', 'BI', 'BJ', 'BL', 'BM', 'BN', 'BO', 'BQ', 'BR', 'BS',
  'BT', 'BV', 'BW', 'BY', 'BZ', 'CA', 'CC', 'CD', 'CF', 'CG', 'CH', 'CI', 'CK', 'CL', 'CM', 'CN',
  'CO', 'CR', 'CU', 'CV', 'CW', 'CX', 'CY', 'CZ', 'DE', 'DJ', 'DK', 'DM', 'DO', 'DZ', 'EC', 'EE',
  'EG', 'EH', 'ER', 'ES', 'ET', 'FI', 'FJ', 'FK', 'FM', 'FO', 'FR', 'GA', 'GB', 'GD', 'GE', 'GF',
  'GG', 'GH', 'GI', 'GL', 'GM', 'GN', 'GP', 'GQ', 'GR', 'GS', 'GT', 'GU', 'GW', 'GY', 'HK', 'HM',
  'HN', 'HR', 'HT', 'HU', 'ID', 'IE', 'IL', 'IM', 'IN', 'IO', 'IQ', 'IR', 'IS', 'IT', 'JE', 'JM',
  'JO', 'JP', 'KE', 'KG', 'KH', 'KI', 'KM', 'KN', 'KP', 'KR', 'KW', 'KY', 'KZ', 'LA', 'LB', 'LC',
  'LI', 'LK', 'LR', 'LS', 'LT', 'LU', 'LV', 'LY', 'MA', 'MC', 'MD', 'ME', 'MF', 'MG', 'MH', 'MK',
  'ML', 'MM', 'MN', 'MO', 'MP', 'MQ', 'MR', 'MS', 'MT', 'MU', 'MV', 'MW', 'MX', 'MY', 'MZ', 'NA',
  'NC', 'NE', 'NF', 'NG', 'NI', 'NL', 'NO', 'NP', 'NR', 'NU', 'NZ', 'OM', 'PA', 'PE', 'PF', 'PG',
  'PH', 'PK', 'PL', 'PM', 'PN', 'PR', 'PS', 'PT', 'PW', 'PY', 'QA', 'RE', 'RO', 'RS', 'RU', 'RW',
  'SA', 'SB', 'SC', 'SD', 'SE', 'SG', 'SH', 'SI', 'SJ', 'SK', 'SL', 'SM', 'SN', 'SO', 'SR', 'SS',
  'ST', 'SV', 'SX', 'SY', 'SZ', 'TC', 'TD', 'TF', 'TG', 'TH', 'TJ', 'TK', 'TL', 'TM', 'TN', 'TO',
  'TR', 'TT', 'TV', 'TW', 'TZ', 'UA', 'UG', 'UM', 'US', 'UY', 'UZ', 'VA', 'VC', 'VE', 'VG', 'VI',
  'VN', 'VU', 'WF', 'WS', 'XK', 'YE', 'YT', 'ZA', 'ZM', 'ZW',
]

const CODE_SET = new Set(COUNTRY_CODES)

/** Is this one of the codes above? Case-insensitive, whitespace-tolerant. */
export function isCountryCode(value: string | null | undefined): boolean {
  return !!value && CODE_SET.has(value.trim().toUpperCase())
}

/**
 * The country's English name, or null.
 *
 * `XK` is spelled out here because ICU's answer for it varies by version and
 * "Kosovo" is what every version means.
 */
export function countryName(code: string | null | undefined): string | null {
  if (!isCountryCode(code)) return null
  const upper = code!.trim().toUpperCase()
  if (upper === 'XK') return 'Kosovo'
  try {
    const name = new Intl.DisplayNames(['en'], { type: 'region' }).of(upper)
    return name && name !== upper ? name : upper
  } catch {
    // A runtime without the region data still knows the code is a country.
    return upper
  }
}

/**
 * Every country as `{ code, name }`, alphabetically by name.
 *
 * Built once per process. Sorted with `localeCompare` so "Åland Islands" files
 * under A rather than after Z.
 */
let sorted: { code: string; name: string }[] | null = null
export function allCountries(): { code: string; name: string }[] {
  if (sorted) return sorted
  sorted = COUNTRY_CODES
    .map((code) => ({ code, name: countryName(code) ?? code }))
    .sort((a, b) => a.name.localeCompare(b.name, 'en'))
  return sorted
}

/**
 * A flag image for a country code.
 *
 * An image rather than the emoji flag, which is the obvious answer and the
 * wrong one here: emoji flags are pairs of regional-indicator letters, and
 * Windows ships no glyphs for them — every flag on the site would render as two
 * boxed letters for a large share of the people reading it. A 20-pixel PNG
 * costs one cached request and looks the same everywhere.
 */
export function countryFlagUrl(code: string | null | undefined, height: 20 | 40 = 20): string | null {
  if (!isCountryCode(code)) return null
  return `https://flagcdn.com/h${height}/${code!.trim().toLowerCase()}.png`
}

/**
 * Read whatever is stored and return a code, or null.
 *
 * Accepts a code outright, and an English country name for the values written
 * while this was a free-text box — so an existing "United States" becomes `US`
 * rather than disappearing from a profile the first time it is displayed.
 */
export function normalizeCountry(value: string | null | undefined): string | null {
  if (!value) return null
  const raw = value.trim()
  if (!raw) return null
  if (isCountryCode(raw)) return raw.toUpperCase()
  const wanted = raw.toLowerCase()
  return allCountries().find((c) => c.name.toLowerCase() === wanted)?.code ?? null
}
